return {
    {
      "nvim-tree/nvim-web-devicons",
      opts = {
        md = { icon = "", name = "Markdown"},
        deb = { icon = "", name = "Deb" },
        lock = { icon = "", name = "Lock" },
        mp3 = { icon = "󰝚", name = "Mp3" },
        mp4 = { icon = "", name = "Mp4" },
        out = { icon = "", name = "Out" },
        ["robots.txt"] = { icon = "ﮧ", name = "Robots" },
        ttf = { icon = "", name = "TrueTypeFont" },
        rpm = { icon = "", name = "Rpm" },
        woff = { icon = "", name = "WebOpenFontFormat" },
        woff2 = { icon = "", name = "WebOpenFontFormat2" },
        xz = { icon = "", name = "Xz" },
        zip = { icon = "", name = "Zip" },
      },
    },
    {
      "onsails/lspkind.nvim",
      opts = {
        mode = "symbol",
        symbol_map = {
          Array = "",
          Boolean = "⊨",
          Class = "",
          Constructor = "",
          Key = "",
          Namespace = "",
          Null = "NULL",
          Number = "#",
          Object = "",
          Package = "󰏗",
          Property = "",
          Reference = "",
          Snippet = "",
          String = "",
          TypeParameter = "",
          Unit = "",
        },
      },
      enabled = vim.g.icons_enabled,
      config = require "plugins.configs.lspkind",
    },
}