####################
#### Font Basic ####
####################

font_family       LXGW WenKai Mono
bold_font         auto
italic_font       auto
bold_italic_font  auto
font_size         17.0

####################
#### Nerd Fonts ####
####################

# Seti-UI + Custom
symbol_map U+E5FA-U+E631 Symbols Nerd Font
# Devicons
symbol_map U+E700-U+E7C5 Symbols Nerd Font
# Font Awesome
symbol_map U+F000-U+F2E0 Symbols Nerd Font
# Font Awesome Extension
symbol_map U+E200-U+E2A9 Symbols Nerd Font
# Material Design
symbol_map U+F500-U+FD46 Symbols Nerd Font
# Weather
symbol_map U+E300-U+E3EB Symbols Nerd Font
# Octicons
symbol_map U+F400-U+F4A9,U+2665,U+26A1 Symbols Nerd Font
# Powerline Symbols
symbol_map U+E0A0-U+E0A2,U+E0B0-U+E0B3 Symbols Nerd Font
# Powerline Extra Symbols
symbol_map U+E0A3,U+E0B4-U+E0C8,U+E0CA,U+E0CC-U+E0D4 Symbols Nerd Font
# IEC Power Symbols
symbol_map U+23FB-U+23FE,U+2B58 Symbols Nerd Font
# Font Logos
symbol_map U+F300-U+F32D Symbols Nerd Font
# Pomicons
symbol_map U+E000-U+E00A Symbols Nerd Font
# Codicons
symbol_map U+EA60-U+EBEB Symbols Nerd Font
